### ISSUE TITLE
missing vids/v.mp4

### ISSUE THREAD

**Issue by aleonnet** [Shr1ftyy/toyslam#1]
Hi @Shr1ftyy,
Could you upload the video file please? vids/v.mp4
I'd like to see your approach in action if possible.

Does it work with indoor elements? I'd like to use it with my Raspberry pi self driving model.

Thank you,

**Comment by sbinabdullah** [comment]
> Hi @Shr1ftyy,
> Could you upload the video file please? vids/v.mp4
> I'd like to see your approach in action if possible.
> 
> Does it work with indoor elements? I'd like to use it with my Raspberry pi self driving model.
> 
> Thank you,

Hello @aleonnet , this implementation is still not complete, I'd recommend taking a look at https://github.com/raulmur/ORB_SLAM2    
OR https://github.com/geohot/twitchslam if your looking for an implementation in python.
